export const GET_PRODUCT="GET_PRODUCT"
export const REQUEST_PRODUCT="REQUEST_PRODUCT"
export const SORT_PRODUCT="SORT_PRODUCT"
export const BUY_PRODUCT="BUY_PRODUCT";
export const CART= "CART"
export const SEARCH_ITEM="SEARCH_ITEM"