export const SIGNIN_LOODING_REQUEST = 'SIGNIN_LOODING_REQUEST'
export const SIGNIN_SUCCESS_REQUEST = 'SIGNIN_SUCCESS_REQUEST'
export const SIGNIN_FAILURE_REQUEST = 'SIGNIN_FAILURE_REQUEST'

export const SIGNUP_LOODING_REQUEST = 'SIGNUP_LOODING_REQUEST'
export const SIGNUP_SUCCESS_REQUEST = 'SIGNUP_SUCCESS_REQUEST'
export const SIGNUP_FAILURE_REQUEST = 'SIGNUP_FAILURE_REQUEST'

export const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST'
